"""migração inicial

Revision ID: 458182c5b5c1
Revises: 
Create Date: 2026-09-04 11:05:41.082408

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458182c5b5c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'aluno', name='papelenum'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('disciplina', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('idioma', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('introducao', sa.Text(), nullable=True),
    sa.Column('resposta', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prova_id', 'numero', 'idioma', name='uq_questoes_prova_numero_idioma')
    )
    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.Column('letra', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questao_id', 'letra', name='uq_alternativa_questao_letra')
    )
    op.create_table('respostas_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('questao_id', sa.Integer(), nullable=True),
    sa.Column('resposta', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('acertou', sa.Boolean(), nullable=False),
    sa.Column('data_resposta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas_usuario')
    op.drop_table('alternativas')
    op.drop_table('questoes')
    op.drop_table('usuarios')
    op.drop_table('provas')
    # ### end Alembic commands ###
