"""empty message

Revision ID: a63aa9da53d5
Revises: 9275761fcdee
Create Date: 2026-08-18 09:43:21.032300

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a63aa9da53d5'
down_revision: Union[str, Sequence[str], None] = '9275761fcdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alternativas', 'texto',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_unique_constraint('uq_alternativa_questao_letra', 'alternativas', ['questao_id', 'letra'])
    op.alter_column('questoes', 'enunciado',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('questoes', 'introducao',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questoes', 'introducao',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('questoes', 'enunciado',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_alternativa_questao_letra', 'alternativas', type_='unique')
    op.alter_column('alternativas', 'texto',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
