"""empty message

Revision ID: bf689db614d8
Revises: 61035f6673e0
Create Date: 2026-08-18 09:27:38.665842

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf689db614d8'
down_revision: Union[str, Sequence[str], None] = '61035f6673e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternativas', sa.Column('arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('alternativas', 'texto',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('questoes', sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('questoes', 'disciplina',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('questoes', 'idioma',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('questoes', 'enunciado',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questoes', 'introducao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('uq_questoes_prova_numero_idioma', 'questoes', ['prova_id', 'numero', 'idioma'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_questoes_prova_numero_idioma', 'questoes', type_='unique')
    op.alter_column('questoes', 'introducao',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questoes', 'enunciado',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questoes', 'idioma',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('questoes', 'disciplina',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('questoes', 'titulo')
    op.alter_column('alternativas', 'texto',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('alternativas', 'arquivo')
    # ### end Alembic commands ###
